/** Matches user-panel COLORS — Astrotalk golden brand */
export const COLORS = {
  primary: '#FDB913',
  primaryDark: '#E5A800',
  primaryLight: '#FFF8E1',
  yellow: '#FFDB4D',
  yellowLight: '#FFF8E1',
  background: '#FFFFFF',
  cream: '#FFFCF8',
  surface: '#FFFFFF',
  card: '#FFFFFF',
  text: '#1A1A1A',
  textSecondary: '#666666',
  textLight: '#999999',
  border: '#E5E5E5',
  borderLight: '#F0F0F0',
  success: '#2EAF5D',
  successLight: '#E8F8EE',
  error: '#E53935',
  errorLight: '#FFEBEE',
  warning: '#F59E0B',
  online: '#2EAF5D',
  offline: '#9CA3AF',
  busy: '#E53935',
  star: '#FDB913',
  chatBtn: '#2EAF5D',
  callBtn: '#2EAF5D',
  bannerDark: '#1E1033',
  bannerDarkEnd: '#2D1B4E',
  overlay: 'rgba(0,0,0,0.45)',
  shadow: 'rgba(0,0,0,0.06)',
  filterNew: '#E0F7FA',
  filterNewText: '#00838F',
  link: '#1976D2',
  continueDisabled: '#E8E8E8',
  continueText: '#AAAAAA',
  logoYellow: '#FDB913',
};

/** Backward-compatible alias used across astro-app screens */
export const colors = {
  bg: COLORS.cream,
  card: COLORS.surface,
  border: COLORS.border,
  primary: COLORS.primary,
  primaryLight: COLORS.yellowLight,
  text: COLORS.text,
  textMuted: COLORS.textSecondary,
  success: COLORS.success,
  danger: COLORS.error,
  warning: COLORS.warning,
  bannerDark: COLORS.bannerDark,
  link: COLORS.link,
};