/** Searchable birth places for kundli / profile forms */
export const BIRTH_PLACES = [
  'New Delhi, Delhi',
  'Mumbai, Maharashtra',
  'Bengaluru, Karnataka',
  'Hyderabad, Telangana',
  'Chennai, Tamil Nadu',
  'Kolkata, West Bengal',
  'Pune, Maharashtra',
  'Ahmedabad, Gujarat',
  'Jaipur, Rajasthan',
  'Lucknow, Uttar Pradesh',
  'Chandigarh, Chandigarh',
  'Indore, Madhya Pradesh',
  'Bhopal, Madhya Pradesh',
  'Patna, Bihar',
  'Ranchi, Jharkhand',
  'Bhubaneswar, Odisha',
  'Guwahati, Assam',
  'Thiruvananthapuram, Kerala',
  'Kochi, Kerala',
  'Coimbatore, Tamil Nadu',
  'Madurai, Tamil Nadu',
  'Nagpur, Maharashtra',
  'Nashik, Maharashtra',
  'Surat, Gujarat',
  'Vadodara, Gujarat',
  'Rajkot, Gujarat',
  'Amritsar, Punjab',
  'Ludhiana, Punjab',
  'Jalandhar, Punjab',
  'Dehradun, Uttarakhand',
  'Haridwar, Uttarakhand',
  'Varanasi, Uttar Pradesh',
  'Kanpur, Uttar Pradesh',
  'Agra, Uttar Pradesh',
  'Noida, Uttar Pradesh',
  'Ghaziabad, Uttar Pradesh',
  'Faridabad, Haryana',
  'Gurgaon, Haryana',
  'Shimla, Himachal Pradesh',
  'Jammu, Jammu & Kashmir',
  'Srinagar, Jammu & Kashmir',
  'Raipur, Chhattisgarh',
  'Jodhpur, Rajasthan',
  'Udaipur, Rajasthan',
  'Kota, Rajasthan',
  'Mysuru, Karnataka',
  'Mangaluru, Karnataka',
  'Hubballi, Karnataka',
  'Visakhapatnam, Andhra Pradesh',
  'Vijayawada, Andhra Pradesh',
  'Warangal, Telangana',
  'Aurangabad, Maharashtra',
  'Goa, Goa',
  'Panaji, Goa',
  'Pondicherry, Puducherry',
  'Imphal, Manipur',
  'Shillong, Meghalaya',
  'Aizawl, Mizoram',
  'Kohima, Nagaland',
  'Gangtok, Sikkim',
  'Itanagar, Arunachal Pradesh',
  'Agartala, Tripura',
  'London, UK',
  'New York, USA',
  'Dubai, UAE',
  'Singapore, Singapore',
  'Toronto, Canada',
  'Sydney, Australia',
  'Melbourne, Australia',
  'Kathmandu, Nepal',
  'Colombo, Sri Lanka',
  'Dhaka, Bangladesh',
];

export function searchPlaces(query, limit = 40) {
  const q = String(query || '').trim().toLowerCase();
  if (!q) return BIRTH_PLACES.slice(0, limit);
  return BIRTH_PLACES.filter((p) => p.toLowerCase().includes(q)).slice(0, limit);
}
